Repository woowacourse-tobi-spring-study/tobi-vol1, pull requests merged in 2021-06, with the labels that each got.

#61 [마이웨이 조] 바다 2장 PR 제출합니다.
  build.gradle
  src/main/java/user/dao/UserDao.java
  src/main/java/user/domain/User.java
  src/test/java/UserDaoTest.java
Labels: 2장, 마이웨이조

#59 [마이웨이 조] 조엘 4장 PR 제출합니다.
  src/main/java/CountingDaoFactory.java
  src/main/java/DaoFactory.java
  src/main/java/DaoFactoryForTest.java
  src/main/java/user/dao/UserDao.java
  src/main/java/user/dao/UserDaoJdbc.java
  src/main/java/user/domain/User.java
  src/test/java/UserDaoEqualityTest.java
  src/test/java/UserDaoTest.java
  src/test/java/UserDaoWithCountingTest.java
Labels: 4장, 마이웨이조

#63 찰리 3장 PR 제출합니다.
  posting/SEASON2-2.md
  src/main/java/springbook/user/User.java
  src/main/java/springbook/user/dao/JdbcContext.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/dao/strategy/statement/StatementStrategy.java
  src/test/java/springbook/learningtest/template/BufferedReaderCallback.java
  src/test/java/springbook/learningtest/template/Calculator.java
  src/test/java/springbook/learningtest/template/CalculatorTest.java
  src/test/java/springbook/learningtest/template/LineCallback.java
  src/test/java/springbook/user/dao/UserDaoTest.java
  src/test/resources/numbers.txt
Labels: 3장, 고양이조

#64 [마이웨이 조] 바다 3장 PR 제출합니다.
  src/main/java/user/dao/StatementStrategy.java
  src/main/java/user/dao/UserDao.java
  src/test/java/UserDaoTest.java
Labels: 3장, 마이웨이조

#58 [고양이조]마크 5장 PR 제출합니다.
  build.gradle
  src/main/java/com/binghe/ch05/AppConfiguration.java
  src/main/java/com/binghe/ch05/dao/UserDao.java
  src/main/java/com/binghe/ch05/dao/UserDaoJdbc.java
  src/main/java/com/binghe/ch05/domain/Level.java
  src/main/java/com/binghe/ch05/domain/User.java
  src/main/java/com/binghe/ch05/service/DummyMailSender.java
  src/main/java/com/binghe/ch05/service/UserService.java
  src/main/resources/schema.sql
  src/test/java/com/binghe/ch05/TestAppConfiguration.java
  src/test/java/com/binghe/ch05/dao/UserDaoTest.java
  src/test/java/com/binghe/ch05/domain/UserTest.java
  src/test/java/com/binghe/ch05/service/MockUserServiceTest.java
  src/test/java/com/binghe/ch05/service/UserServiceTest.java
Labels: 5장, 고양이조

#65 [앵무조였던] 찰리 4장 PR 제출합니다.
  posting/SEASON2-1.md
  posting/TobySpring-1.md
  posting/TobySpring-3.md
  posting/TobySpring-4.md
  posting/img_1.png
  src/main/java/springbook/UserDaoConnectionCountingTest.java
  src/main/java/springbook/user/dao/CountingDaoFactory.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/DaoFactoryTest.java
  src/main/java/springbook/user/dao/DuplicateUserIdException.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/dao/UserDaoJdbc.java
  src/main/resources/applicationContext.xml
  src/test/java/springbook/user/dao/UserDaoJdbcTest.java
  src/test/resources/test-applicationContext.xml
Labels: 4장, 앵무새조

#66 [마이웨이 조] 조엘 5장 PR 제출합니다.
  build.gradle
  sql/ddl.sql
  src/main/java/CountingDaoFactory.java
  src/main/java/DaoFactory.java
  src/main/java/user/CountingDaoFactory.java
  src/main/java/user/DaoFactory.java
  src/main/java/user/DaoFactoryForTest.java
  src/main/java/user/dao/UserDao.java
  src/main/java/user/dao/UserDaoJdbc.java
  src/main/java/user/domain/Level.java
  src/main/java/user/domain/User.java
  src/main/java/user/service/DummyMailSender.java
  src/main/java/user/service/MockMailSender.java
  src/main/java/user/service/UserService.java
  src/test/java/training/StringReplaceTest.java
  src/test/java/training/template/BufferedReaderCallback.java
  src/test/java/training/template/Calculator.java
  src/test/java/training/template/CalculatorTest.java
  src/test/java/training/template/LineCallback.java
  src/test/java/user/dao/UserDaoEqualityTest.java
  src/test/java/user/dao/UserDaoTest.java
  src/test/java/user/dao/UserDaoWithCountingTest.java
  src/test/java/user/domain/UserTest.java
  src/test/java/user/service/TestUserService.java
  src/test/java/user/service/TestUserServiceException.java
  src/test/java/user/service/UserServiceTest.java
Labels: 5장, 마이웨이조
