Repository woowacourse-tobi-spring-study/tobi-vol1, pull requests merged in 2021-05, with the labels that each got.

#6 [파즈 조][조엘]1장 1주차 PR 제출합니다.
  sql/ddl.sql
  src/main/java/DaoFactory.java
  src/main/java/UserDaoTest.java
  src/main/java/empty.txt
  src/main/java/user/domain/ConnectionMaker.java
  src/main/java/user/domain/SimpleConnectionMaker.java
  src/main/java/user/domain/User.java
  src/main/java/user/domain/UserDao.java
  src/test/java/empty.txt
Labels: 파즈조

#2 [파즈 조][파즈]1장 1주차 PR 제출합니다.
  src/main/java/Application.java
  src/main/java/dao/ConnectionMaker.java
  src/main/java/dao/DConnectionMaker.java
  src/main/java/dao/DaoFactory.java
  src/main/java/dao/NConnectionMaker.java
  src/main/java/dao/SimpleConnectionMaker.java
  src/main/java/dao/UserDao.java
  src/main/java/dao/UserDaoTest.java
  src/main/java/domain/User.java
Labels: 파즈조

#4 [파즈 조][케빈]1장 1주차 PR 제출합니다.
  src/main/java/springbook/dao/DaoFactory.java
  src/main/java/springbook/dao/connection/AnotherConnectionMaker.java
  src/main/java/springbook/dao/connection/ConnectionMaker.java
  src/main/java/springbook/dao/connection/SimpleConnectionMaker.java
  src/main/java/springbook/dao/user/UserDao.java
  src/main/java/springbook/domain/user/User.java
  src/main/java/springbook/test/UserDaoTest.java
Labels: 파즈조

#9 [나봄 조][욘]1장 1주차 PR 제출합니다.
  src/main/java/Application.java
  src/main/java/dao/ConnectionMaker.java
  src/main/java/dao/DConnectionMaker.java
  src/main/java/dao/DaoFactory.java
  src/main/java/dao/SimpleConnectionMaker.java
  src/main/java/dao/UserDao.java
  src/main/java/dao/UserDaoTest.java
  src/main/java/domain/User.java
Labels: 나봄조

#11 [검프 조][찰리] 1장 1주차 PR 제출합니다.
  src/main/java/springbook/UserDaoTest.java
  src/main/java/springbook/user/User.java
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
Labels: 검프조

#12 [검프 조][검프] 1장 1주차 PR 제출합니다.
  src/main/java/chapter01/Application.java
  src/main/java/chapter01/DaoFactory.java
  src/main/java/chapter01/UserDaoTest.java
  src/main/java/chapter01/dao/AccountDao.java
  src/main/java/chapter01/dao/Connections.java
  src/main/java/chapter01/dao/DConnections.java
  src/main/java/chapter01/dao/MessageDao.java
  src/main/java/chapter01/dao/NConnections.java
  src/main/java/chapter01/dao/SimpleConnectionMasker.java
  src/main/java/chapter01/dao/UserDao.java
  src/main/java/chapter01/domain/User.java
  src/main/java/chapter01/schema/schema.sql
  src/main/java/empty.txt
Labels: 검프조

#14 [검프 조][조앤] 1장 1주차 PR 제출합니다.
  build.gradle
  src/main/java/Main.java
  src/main/java/empty.txt
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/dao/WoowaConnectionMaker.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/schema.sql
  src/test/java/springbook/user/dao/UserDaoTest.java
Labels: 검프조

#15 [나봄 조][나봄]1장 1주차 PR 제출합니다.
  src/main/java/user/dao/chaos/UserDao.java
  src/main/java/user/dao/di/ConnectionMaker.java
  src/main/java/user/dao/di/UserDaoEx.java
  src/main/java/user/dao/templateMethod/UserDao.java
  src/main/java/user/dao/templateMethod/UserDaoEx.java
  src/main/java/user/domain/User.java
Labels: 나봄조

#18 [나봄 조][완태]1장 1주차 PR 제출합니다.
  docker-compose.yaml
  src/main/java/ConnectionMaker.java
  src/main/java/ConnectionMakerImpl.java
  src/main/java/DaoFactory.java
  src/main/java/User.java
  src/main/java/UserDao.java
  src/main/java/empty.txt
  src/main/resources/schema.sql
  src/test/java/UserDaoTest.java
Labels: 나봄조

#19 [파즈 조][코다]1장 1주차 PR 제출합니다.
  src/main/java/UserDaoTest.java
  src/main/java/dao/ConnectionMaker.java
  src/main/java/dao/MysqlConnection.java
  src/main/java/dao/MysqlUserDao.java
  src/main/java/dao/SimpleConnectionMaker.java
  src/main/java/dao/UserDao.java
  src/main/java/domain/DaoFactory.java
  src/main/java/domain/User.java
Labels: 파즈조

#20 [나봄 조][라이언]1장 1주차 PR 제출합니다.
  README.md
  src/main/java/springbook/user/UserDaoTest.java
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
Labels: 나봄조

#21 [나봄 조][손너잘]1장 1주차 PR 제출합니다.
  build.gradle
  src/main/java/step1/README.md
  src/main/java/step1/user/Application.java
  src/main/java/step1/user/dao/ConnectionMaker.java
  src/main/java/step1/user/dao/DConnectionMaker.java
  src/main/java/step1/user/dao/DaoFactory.java
  src/main/java/step1/user/dao/NConnectionMaker.java
  src/main/java/step1/user/dao/UserDao.java
  src/main/java/step1/user/domain/User.java
  src/main/resources/schema.sql
Labels: 나봄조

#13 [검프 조][멍토] 1장 1주차 PR 제출합니다.
  build.gradle
  docs/토비의 스프링 Vol1  94p.md
  docs/토비의 스프링 Vol1 143p.md
  src/main/java/empty.txt
  src/main/java/springbook/user/Application.java
  src/main/java/springbook/user/dao/AccountDao.java
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/CountingConnectionMaker.java
  src/main/java/springbook/user/dao/CountingDaoFactory.java
  src/main/java/springbook/user/dao/DConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/MessageDao.java
  src/main/java/springbook/user/dao/NConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/dao/UserDaoConnectionCountingTest.java
  src/main/java/springbook/user/dao/UserDaoTest.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/applicationContext.xml
Labels: 검프조

#3 [웨지 조][웨지]1장 1주차 PR 제출합니다.
  src/main/java/empty.txt
  src/main/java/springbook/user/dao/BaeminSimpleConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/NaverSimpleConnectionMaker.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
  src/test/java/empty.txt
  src/test/java/springbook/user/dao/UserDaoTest.java
Labels: 웨지조

#17 [웨지 조][바다]1장 1주차 PR 제출합니다.
  build.gradle
  src/main/java/empty.txt
  src/main/java/user/UserApplication.java
  src/main/java/user/dao/ConnectionMaker.java
  src/main/java/user/dao/DConnectionMaker.java
  src/main/java/user/dao/DUserDao.java
  src/main/java/user/dao/DaoFactory.java
  src/main/java/user/dao/NUserDao.java
  src/main/java/user/dao/SimpleConnectionMaker.java
  src/main/java/user/dao/UserDao.java
  src/main/java/user/domain/User.java
Labels: 웨지조

#10 [검프 조][피카]1장 1주차 PR 제출합니다.
  build.gradle
  src/main/java/Application.java
  src/main/java/dao/abstract_class/DUserDao.java
  src/main/java/dao/abstract_class/NUserDao.java
  src/main/java/dao/abstract_class/UserDao.java
  src/main/java/dao/class_separate/ConnectionMaker.java
  src/main/java/dao/class_separate/DConnectionMaker.java
  src/main/java/dao/class_separate/NConnectionMaker.java
  src/main/java/dao/class_separate/UserDao.java
  src/main/java/dao/ioc/ConnectionMaker.java
  src/main/java/dao/ioc/DConnectionMaker.java
  src/main/java/dao/ioc/DaoFactory.java
  src/main/java/dao/ioc/NConnectionMaker.java
  src/main/java/dao/ioc/UserDao.java
  src/main/java/domain/User.java
  src/main/resources/application.properties
  src/main/resources/db/h2/data.sql
  src/main/resources/db/h2/schema.sql
  src/test/java/abstract_class/UserDaoTest.java
  src/test/java/class_separate/UserDaoTest.java
  src/test/java/ioc/UserDaoTest.java
Labels: 검프조

#16 [웨지 조][오즈]1장 1주차 PR 제출합니다.
  src/main/java/springbook/UserDaoTest.java
  src/main/java/springbook/user/dao/AccountDao.java
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/DConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/MessageDao.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
Labels: 웨지조

#22 [파즈 조][조이]1장 1주차 PR 제출합니다.
  .gitignore
  src/main/java/Application.java
  src/main/java/empty.txt
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/DConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
  tobi-docker/docker-compose.yml
Labels: 파즈조

#32 [웨지 조][마크]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/com/binghe/user/dao/spring_ioc/DaoFactory.java
  src/main/java/com/binghe/user/dao/spring_ioc/UserDao.java
  src/main/resources/applicationContext.xml
  src/test/java/com/binghe/user/dao/spring_ioc/UserDaoTest.java
  src/test/java/com/binghe/user/dao/spring_ioc/XmlUserDaoTest.java
Labels: 1장 2주차, 웨지조

#29 [웨지 조][웨지]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/springbook/user/dao/BaeminSimpleConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/NaverSimpleConnectionMaker.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/applicationContext.xml
  src/test/java/springbook/user/dao/UserDaoTest.java
Labels: 1장 2주차, 웨지조

#31 [웨지 조][오즈]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/springbook/UserDaoTest.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/resources/applicationContext.xml
Labels: 1장 2주차, 웨지조

#25 [나봄 조][욘]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/dao/DaoFactory.java
  src/main/java/dao/UserDao.java
  src/main/java/dao/UserDaoTest.java
  src/main/java/dao/dumpDao/ConnectionMaker.java
  src/main/java/dao/dumpDao/DConnectionMaker.java
  src/main/java/dao/dumpDao/SimpleConnectionMaker.java
  src/main/java/empty.txt
Labels: 나봄조

#26 [파즈 조][케빈]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/springbook/dao/CountingDaoFactory.java
  src/main/java/springbook/dao/DaoFactory.java
  src/main/java/springbook/dao/UserDao.java
  src/main/java/springbook/dao/connection/CountingConnectionMaker.java
  src/main/java/springbook/dao/user/UserDao.java
  src/main/java/springbook/domain/user/User.java
  src/main/java/springbook/test/UserDaoAnnotationTest.java
  src/main/java/springbook/test/UserDaoXmlTest.java
  src/main/resources/applicationContext.xml
  src/main/resources/test-applicationContext.xml
  src/test/java/springbook/dao/LearningTest.java
  src/test/java/springbook/dao/UserDaoTest.java
Labels: 파즈조

#28 [검프 조][멍토]1장 2주차 PR 제출합니다.
  build.gradle
  docs/토비의 스프링 Vol1  94p.md
  docs/토비의 스프링 Vol1 143p.md
  src/main/java/empty.txt
  src/main/java/springbook/user/Application.java
  src/main/java/springbook/user/dao/AccountDao.java
  src/main/java/springbook/user/dao/ConnectionMaker.java
  src/main/java/springbook/user/dao/CountingConnectionMaker.java
  src/main/java/springbook/user/dao/CountingDaoFactory.java
  src/main/java/springbook/user/dao/DConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/MessageDao.java
  src/main/java/springbook/user/dao/NConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/dao/UserDaoConnectionCountingTest.java
  src/main/java/springbook/user/dao/UserDaoTest.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/applicationContext.xml
Labels: 검프조

#30 [나봄 조][나봄]1장 2주차 PR 제출합니다.
  build.gradle
  gradlew
  src/main/java/tobi1/user/dao/chaos/UserDao.java
  src/main/java/tobi1/user/dao/di/ConnectionMaker.java
  src/main/java/tobi1/user/dao/di/UserDaoEx.java
  src/main/java/tobi1/user/dao/templateMethod/UserDao.java
  src/main/java/tobi1/user/dao/templateMethod/UserDaoEx.java
  src/main/java/tobi1/user/domain/User.java
  src/main/java/tobi2/user/ConnectionMaker.java
  src/main/java/tobi2/user/DaoFactory.java
  src/main/java/tobi2/user/User.java
  src/main/java/tobi2/user/UserDao.java
Labels: 1장 2주차, 나봄조

#33 [나봄 조][라이언]1장 2주차 PR 제출합니다.
  README.md
  build.gradle
  src/main/java/springbook/user/UserDaoTest.java
  src/main/java/springbook/user/dao/CountingConnectionMaker.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/SimpleConnectionMaker.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/resources/schema.sql
Labels: 나봄조

#34 [웨지 조][다니]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/empty.txt
  src/main/java/springbook/dao/ConnectionMaker.java
  src/main/java/springbook/dao/CountingConnectionMaker.java
  src/main/java/springbook/dao/CountingDaoFactory.java
  src/main/java/springbook/dao/DaoFactory.java
  src/main/java/springbook/dao/SimpleConnectionMaker.java
  src/main/java/springbook/dao/UserDao.java
  src/main/java/springbook/dao/UserDaoCountingConnectionTest.java
  src/main/java/springbook/dao/UserDaoTest.java
  src/main/java/springbook/dao/UserDaoTestUtils.java
  src/main/java/springbook/domain/User.java
  src/test/java/empty.txt
Labels: 1장 2주차, 웨지조

#35 [검프 조][찰리] 1장 2주차 PR 제출합니다.
  build.gradle
  posting/SEASON1-2.md
  posting/img.png
  src/main/java/empty.txt
  src/main/java/springbook/UserDaoConnectionCountingTest.java
  src/main/java/springbook/UserDaoTest.java
  src/main/java/springbook/user/dao/CountingConnectionMaker.java
  src/main/java/springbook/user/dao/CountingDaoFactory.java
  src/main/java/springbook/user/dao/DaoFactory.java
  src/main/java/springbook/user/dao/DaoFactoryTest.java
  src/main/java/springbook/user/dao/SingletonUserDao.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/resources/applicationContext.xml
Labels: 1장 2주차, 검프조

#36 [파즈 조][코다]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/UserDaoTest.java
  src/main/java/dao/CountingConnectionMaker.java
  src/main/java/dao/UserDao.java
  src/main/java/domain/CountingDaoFactory.java
  src/main/java/domain/DaoFactory.java
  src/main/resources/applicationContext.xml
Labels: 1장 2주차, 파즈조

#41 [검프 조][피카]1장 2주차 PR 제출합니다.
  build.gradle
  src/main/java/dao/counting/ConnectionMaker.java
  src/main/java/dao/counting/CountingConnectionMaker.java
  src/main/java/dao/counting/CountingDaoFactory.java
  src/main/java/dao/counting/DConnectionMaker.java
  src/main/java/dao/counting/UserDao.java
  src/test/java/dao/abstract_class/UserDaoTest.java
  src/test/java/dao/class_separate/UserDaoTest.java
  src/test/java/dao/counting/UserDaoConnectionCountingTest.java
  src/test/java/dao/ioc/UserDaoTest.java
Labels: 1장 2주차, 검프조

#43 [고양이 조][케빈]2장, 3장 PR 제출합니다.
  build.gradle
  src/main/java/springbook/dao/JdbcContext.java
  src/main/java/springbook/dao/UserDao.java
  src/main/java/springbook/dao/strategy/DeleteAllStatement.java
  src/main/java/springbook/dao/strategy/StatementStrategy.java
  src/main/java/springbook/domain/user/User.java
  src/main/java/springbook/learningtest/BufferedReaderCallback.java
  src/main/java/springbook/learningtest/Calculator.java
  src/main/java/springbook/learningtest/LineCallback.java
  src/test/java/springbook/dao/LearningTest.java
  src/test/java/springbook/dao/UserDaoTest.java
  src/test/java/springbook/learningtest/CalculatorTest.java
  src/test/resources/numbers.txt
Labels: 2장, 3장, 고양이조

#45 [앵무새 조][파즈]2장 PR 제출합니다.
  build.gradle
  src/main/java/dao/UserDao.java
  src/main/java/dao/UserDaoTest.java
  src/test/java/dao/UserDaoTest.java
Labels: 2장, 앵무새조

#47 [고양이조] 웨지 2장, 3장 제출합니다
  build.gradle
  src/main/java/springbook/learningtest/template/Calculator.java
  src/main/java/springbook/learningtest/template/LineCallback.java
  src/main/java/springbook/learningtest/template/numbers.txt
  src/main/java/springbook/user/dao/StatementStrategy.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/junit.xml
  src/main/resources/test-applicationContext.xml
  src/test/java/springbook/learningtest/junit/JunitTest.java
  src/test/java/springbook/learningtest/template/CalcSumTest.java
  src/test/java/springbook/user/dao/UserDaoTest.java
Labels: 2장, 고양이조

#48 [고양이 조][오즈]2장, 3장 PR 제출합니다.
  build.gradle
  src/main/java/springbook/UserDaoTest.java
  src/main/java/springbook/learningtest/template/BufferedReaderCallback.java
  src/main/java/springbook/learningtest/template/Calculator.java
  src/main/java/springbook/learningtest/template/LineCallback.java
  src/main/java/springbook/user/dao/AddStatement.java
  src/main/java/springbook/user/dao/DeleteAllStatement.java
  src/main/java/springbook/user/dao/JdbcContext.java
  src/main/java/springbook/user/dao/StatementStrategy.java
  src/main/java/springbook/user/dao/UserDao.java
  src/main/java/springbook/user/domain/User.java
  src/main/resources/junit.xml
  src/main/resources/numbers.txt
  src/main/resources/test-applicationContext.xml
  src/test/java/springbook/learningtest/junit/JUnitTest.java
  src/test/java/springbook/learningtest/template/CalcSumTest.java
  src/test/java/springbook/user/dao/UserDaoTest.java
Labels: 2장, 3장, 고양이조

#52 [마이웨이 조][조엘]3장 PR 제출합니다.
  build.gradle
  src/main/java/CountingDaoFactory.java
  src/main/java/DaoFactory.java
  src/main/java/DaoFactoryForTest.java
  src/main/java/user/dao/JdbcContext.java
  src/main/java/user/dao/UserDao.java
  src/main/java/user/dao/statement/AddStatement.java
  src/main/java/user/dao/statement/DeleteAllStatement.java
  src/main/java/user/dao/statement/StatementStrategy.java
  src/test/java/StringReplaceTest.java
  src/test/java/UserDaoTest.java
  src/test/java/UserDaoWithCountingTest.java
  src/test/java/template/BufferedReaderCallback.java
  src/test/java/template/Calculator.java
  src/test/java/template/CalculatorTest.java
  src/test/java/template/LineCallback.java
  src/test/resources/numbers.txt
Labels: 3장, 마이웨이조

#54 [고양이조] 케빈 4장 PR 제출합니다.
  src/main/java/springbook/dao/DaoFactory.java
  src/main/java/springbook/dao/UserDao.java
  src/main/java/springbook/dao/UserDaoJdbc.java
  src/main/java/springbook/test/UserDaoAnnotationTest.java
  src/main/java/springbook/test/UserDaoXmlTest.java
  src/main/resources/applicationContext.xml
  src/main/resources/test-applicationContext.xml
  src/test/java/springbook/dao/UserDaoJdbcTest.java
Labels: 4장, 고양이조

#55 [고양이조] 마크 4장 PR 제출합니다.
  src/main/java/com/binghe/ch04/DaoFactory.java
  src/main/java/com/binghe/ch04/dao/UserDao.java
  src/main/java/com/binghe/ch04/dao/UserDaoJdbc.java
  src/main/java/com/binghe/ch04/domain/User.java
  src/test/java/com/binghe/ch04/dao/UserDaoTest.java
Labels: 4장, 고양이조
